#!/bin/bash
# System invariant checker — runs the register in INVARIANTS.md (I1-I5).
# "The repo IS the system" as a verified property, not a slogan: one
# deterministic, read-only pass that the live system still corresponds
# to the repos. Run at the end of every operational session; a FAIL is
# a finding to fix or register, never to ignore.
#   usage: invariant-check.sh             run all invariants
#          invariant-check.sh --hash      I3 also re-hashes staged artifacts
#          invariant-check.sh --baseline  (re)pin the I1 baseline of
#                                         currently-unaccounted files
#                                         (do this only after triaging them)
# Instance resolution (three-repo split): honors $LFS_OPS (private build
# scripts + baseline) and $LFS_LEDGER (live provenance ledger), like
# verify-source.sh. Checks that need the live system (I1-I4) self-skip
# off-instance so the blueprint copy stays runnable anywhere.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
PKGDB=/var/lib/lfs-pkg
OPS="${LFS_OPS:-}"
LEDGER="${LFS_LEDGER:-$REPO/ops/sources-sha256.txt}"
BASELINE="${OPS:-$REPO}/ops/manifest-baseline.txt"
MODE="${1:-}"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
fails=0

# ---------- I1: every binary/library file is accounted for -----------
# Scope: files+symlinks under the binary/library roots. Accounted =
# listed in a package manifest, or in the pinned baseline (pre-existing
# gaps, see INVARIANTS.md limitations).
if [ -d "$PKGDB" ]; then
  scope=""
  for d in /usr/bin /usr/sbin /usr/lib /usr/lib64 /usr/libexec; do
    [ -d "$d" ] && scope="$scope $d"
  done
  # shellcheck disable=SC2086
  find $scope \( -type f -o -type l \) 2>/dev/null | sort > "$TMP/live"
  { cat "$PKGDB"/*.list 2>/dev/null
    grep -hv '^#' "$BASELINE" 2>/dev/null || true
  } | sort -u > "$TMP/accounted"
  comm -23 "$TMP/live" "$TMP/accounted" > "$TMP/unaccounted"
  n=$(wc -l < "$TMP/unaccounted")
  if [ "$MODE" = "--baseline" ]; then
    { echo "# I1 baseline — files that predate manifest coverage, pinned as found"
      echo "# (same trade as the provenance ledger: this proves nothing about how"
      echo "# they got here, it only makes NEW unaccounted files detectable)."
      echo "# Generated by invariant-check.sh --baseline; shrink it by backfilling"
      echo "# manifests, never grow it without triage. INVARIANTS.md has the plan."
      comm -23 "$TMP/live" <(cat "$PKGDB"/*.list 2>/dev/null | sort -u)
    } > "$BASELINE"
    echo "I1 baseline pinned: $(grep -cv '^#' "$BASELINE") files -> $BASELINE (commit it)"
    exit 0
  fi
  if [ "$n" -eq 0 ]; then
    echo "I1 PASS: all files under$scope are manifested or baselined"
  else
    echo "I1 FAIL: $n file(s) not in any manifest or the baseline:"
    head -20 "$TMP/unaccounted" | sed 's/^/  /'
    [ "$n" -gt 20 ] && echo "  ... ($n total)"
    fails=$((fails+1))
  fi
else
  echo "I1 SKIP: $PKGDB not present (not on the live system)"
fi

# ---------- I2: every manifest traces to a build script --------------
if [ -d "$PKGDB" ]; then
  i2=0
  for l in "$PKGDB"/*.list; do
    name=$(basename "$l" .list)
    hit=$(find "$REPO/build" ${OPS:+"$OPS/build"} -name "$name.sh" -print -quit 2>/dev/null)
    if [ -z "$hit" ]; then
      echo "I2 FAIL: manifest $name has no build script in the repos"
      i2=1
    fi
  done
  if [ $i2 -eq 0 ]; then
    echo "I2 PASS: all $(ls "$PKGDB"/*.list | wc -l) manifests trace to a build script"
  else
    fails=$((fails+1))
  fi
else
  echo "I2 SKIP: $PKGDB not present"
fi

# ---------- I3: every staged source artifact is ledger-pinned --------
if [ -d /sources ]; then
  i3=0; cnt=0
  while IFS= read -r f; do
    cnt=$((cnt+1))
    b=$(basename "$f")
    lhash=$(awk -v b="$b" '{n=split($2,p,"/"); if (p[n]==b) print $1}' "$LEDGER" | head -1)
    if [ -z "$lhash" ]; then
      echo "I3 FAIL: $f staged but not in the ledger"
      i3=1
    elif [ "$MODE" = "--hash" ]; then
      sha=$(sha256sum "$f" | awk '{print $1}')
      if [ "$sha" != "$lhash" ]; then
        echo "I3 FAIL: $f sha256 MISMATCH vs ledger — supply-chain event, investigate"
        i3=1
      fi
    fi
  done < <(find /sources -maxdepth 2 -type f \
             \( -name '*.tar.*' -o -name '*.tgz' -o -name '*.txz' \
                -o -name '*.zip' -o -name '*.deb' \) 2>/dev/null)
  if [ $i3 -eq 0 ]; then
    echo "I3 PASS: all $cnt staged artifacts are ledger-pinned${MODE:+ ($MODE)}"
  else
    fails=$((fails+1))
  fi
else
  echo "I3 SKIP: /sources not present"
fi

# ---------- I4: monitoring coverage (delegate) -----------------------
if [ -d /usr/local/bin ]; then
  if bash "$REPO/scripts/coverage-check.sh" > "$TMP/cov" 2>&1; then
    echo "I4 PASS: $(tail -1 "$TMP/cov")"
  else
    echo "I4 FAIL: coverage-check reports:"
    sed 's/^/  /' "$TMP/cov"
    fails=$((fails+1))
  fi
else
  echo "I4 SKIP: not on the live system"
fi

# ---------- I5: build-script hygiene ---------------------------------
# (a) set -euo pipefail in every build script except the legacy phase
#     runners; (b) package scripts ([0-9]*.sh) are one-command-per-line:
#     no && chains outside the two known-safe idioms.
i5=0
while IFS= read -r s; do
  if ! grep -q 'set -euo pipefail' "$s"; then
    echo "I5 FAIL: missing 'set -euo pipefail': $s"
    i5=1
  fi
done < <(find "$REPO/build" ${OPS:+"$OPS/build"} -name '*.sh' \
           ! -name 'run-all.sh' ! -name 'download.sh' 2>/dev/null)
find "$REPO/build" ${OPS:+"$OPS/build"} -name '[0-9]*.sh' -print0 2>/dev/null \
  | xargs -0 grep -nE '&&' 2>/dev/null \
  | grep -vE '&& pwd\)|\[[^]]*\] && echo |&& (break|continue)$|^[^:]+:[0-9]+: *#' > "$TMP/chains" || true
if [ -s "$TMP/chains" ]; then
  echo "I5 FAIL: && chain(s) in package scripts (one command per line):"
  sed 's/^/  /' "$TMP/chains"
  i5=1
fi
if [ $i5 -eq 0 ]; then
  echo "I5 PASS: build scripts have pipefail and no && chains"
else
  fails=$((fails+1))
fi

# ---------------------------------------------------------------------
echo "---"
if [ $fails -eq 0 ]; then
  echo "invariants OK: the system still refines the repos"
else
  echo "invariants FAILED: $fails of 5 — fix or register before ending the session"
fi
exit $fails
